server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mail-service #${DATASOURCE_URL}
    username: mail-service-user #${DATASOURCE_USERNAME}
    password: mail-service-password #${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
  jackson:
    default-property-inclusion: non_null
  mvc:
    format:
      date-time: iso

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openapi.yaml
