CREATE TABLE mailing_categories (
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
CREATE UNIQUE INDEX mailing_categories_name ON mailing_categories (UPPER(name));

CREATE TABLE mailings (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mailing_category_id INTEGER NOT NULL REFERENCES mailing_categories (id),
    recipient_name      TEXT NOT NULL,
    recipient_zip_code  VARCHAR(6) NOT NULL,
    recipient_address   TEXT NOT NULL
);

CREATE TABLE post_offices (
    id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name     TEXT NOT NULL,
    zip_code VARCHAR(6) NOT NULL,
    UNIQUE (name, zip_code)
);
CREATE INDEX post_offices_name ON post_offices (UPPER(name));

CREATE TABLE delivery_statuses (
    id   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL
);
CREATE UNIQUE INDEX delivery_statuses_name ON delivery_statuses (UPPER(name));

CREATE TABLE mailing_statuses (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mailing_id      UUID NOT NULL REFERENCES mailings (id),
    post_office_id  UUID NOT NULL REFERENCES post_offices (id),
    delivery_status INTEGER NOT NULL REFERENCES delivery_statuses (id),
    added_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX mailing_statuses_mailing_id ON mailing_statuses (mailing_id);

INSERT INTO mailing_categories (name)
VALUES ('Письмо'),
       ('Посылка'),
       ('Бандероль'),
       ('Открытка');

INSERT INTO delivery_statuses (name)
VALUES ('Зарегистировано'),
       ('Отправлено'),
       ('Прибыло в промежуточной пункт'),
       ('Покинуло промежуточной пункт'),
       ('Доставлено'),
       ('Вручено');